### ISSUE TITLE
Still not celar to me how dangerous this is

### ISSUE THREAD

**Issue by jpic** [nebstrebor/django-threadlocals#6]
Hi !

Thanks for maintaining this awesome patch, it works for me with AsgiRequest in Django 1.10.7 <3

I've used this app and technique a few times but never had a problem. From what I understand, this would have been subject to errors in old Python versions.

What python versions have an issue with thread locals if any and are they still supported by django?

Thanks <3

**Comment by nebstrebor** [comment]
There isn't a code issue with threadlocals and particular versions of python or django. There is a philospophical issue -- the opinion of many is that thread-locals are the python/django equivalent of using global variables and they have a point. Use of global variables is considered a bad coding practice - CS 101.   If you understand that and still find the library useful then that's why its here.
